# -*- coding: utf-8 -*-
"""Calculadora

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_IBUaPJMwZVhbyzb3inLLhYxwObBlCJ7

#CALCULADORA SIMPLE
"""

print("MENÚ")
print("1. Suma")
print("2. Resta")
print("3. Multiplicación")
print("4. División")

#Ingresar datos
opciones=input("Ingrese la opción deseada del menú:")
numero_uno=float(input("Ingrese el primer número:"))
numero_dos=float(input("Ingrese el segundo número:"))

#Opciones de operación:
if opciones=="1":
  print("Sumamos los dos valores ingreados:")
  print('La suma es:',numero_uno+numero_dos)

if opciones=="2":
  print("Restamos los dos valores ingreados:")
  print(numero_uno-numero_dos)

if opciones=="3":
  print("Multiplicamos los dos valores ingreados:")
  print(numero_uno*numero_dos)

if opciones=="4":
  print("Dividimos los dos valores ingreados:")
  if numero_dos==0:
    print("No se puede dividir por cero")
  else:
    (print(numero_uno/numero_dos))

"""#CALCULADORA MÁS AVANZADA"""

import math

print("MENÚ")
print("1. Suma (+)")
print("2. Resta (-)")
print("3. Multiplicación (*)")
print("4. División(/)")
print("5. Potencia(**)")
print("6. Raíz cuadrada(math.sqrt)")
print("7. Logaritmo(log10)")
print("8. Seno (sin)")
print("9. Coseno (cos)")
print("10. Tangente(tan)")
print("11. raíz cúbica (math.cbrt)")

#Ingresar datos
opciones=input("Ingrese la opción deseada del menú:")
numero_uno=float(input("Ingrese el primer número:"))
numero_dos=float(input("Ingrese el segundo número:"))

#Opciones de operación:
if opciones=="1":
  print("Sumamos los dos valores ingreados:")
  print('La suma es:',numero_uno+numero_dos)

if opciones=="2":
  print("Restamos los dos valores ingreados:")
  print(numero_uno-numero_dos)

if opciones=="3":
  print("Multiplicamos los dos valores ingreados:")
  print(numero_uno*numero_dos)

if opciones=="4":
  print("Dividimos los dos valores ingreados:")
  if numero_dos==0:
    print("No se puede dividir por cero")
  else:
    (print(numero_uno/numero_dos))

if opciones=="5":
  print("Elevamos el primer valor al segundo:")
  print(numero_uno**numero_dos)

if opciones=="6":
  print("Calculamos la raíz cuadrada del primer valor ingresado:")
  print(math.sqrt(numero_uno))

if opciones=="7":
  print("Calculamos el logaritmo (log10) del primer valor ingresado:")
  #print(math.log(numero_uno))

  if numero_uno>0:
    print(math.log(numero_uno))
  else:
    print("Solo existe el logaritmo de un úmero mayor cero")


if opciones=="8":
  print("Calculamos el seno (sin) del primer valor ingresado:")
  print(math.sin(numero_uno))

if opciones=="9":
  print("Calculamos el coseno (cos) del primer valor ingreado:")
  print(math.cos(numero_uno))

if opciones=="10":
  print("Calculamos la tangente (tan) del primer valor ingresado:")
  print(math.tan(numero_uno))

if opciones=="11":
  print("Calculamos la raíz cúbica (math.cbrt) del primer valor ingresado:")
  print(math.cbrt(numero_uno))

import math

def mostrar_titulo():
  print('CALCULADORA AVANZADA')

def mostrar_menu():
  print("MENU")
  print("1. Suma (+)")
  print("2. Resta (-)")
  print("3. Multiplicacion (*)")
  print("4. Division(/)")
  print("5. Potencia(**)")
  print("6. Raiz cuadrada(math.sqrt)")
  print("7. Logaritmo(log10)")
  print("8. Seno (sin)")
  print("9. Coseno (cos)")
  print("10. Tangente(tan)")
  print("11. Raiz cubica (math.cbrt)")

def ingresar_datos():
  opciones=input("Ingrese la opcion deseada del menu:")
  numero_uno=float(input("Ingrese el primer numero:"))
  numero_dos=float(input("Ingrese el segundo numero:"))
  return opciones,numero_uno,numero_dos

def calcular_suma(numero_uno,numero_dos):
  return numero_uno+numero_dos

def calcular_resta(numero_uno,numero_dos):
  return numero_uno-numero_dos

def calcular_multiplicacion(numero_uno,numero_dos):
  return numero_uno*numero_dos

def calcular_division(numero_uno,numero_dos):
  if numero_dos==0:
    print("No se puede dividir por cero")
  else:
    return numero_uno/numero_dos

def calcular_potencia(numero_uno,numero_dos):
  return numero_uno**numero_dos

def calcular_raiz_cuadrada(numero_uno):
  if numero_uno>0:
    return math.sqrt(numero_uno)
  else:
    print("Solo existe la raíz cuadrada de un úmero mayor cero")

def calcular_logaritmo(numero_uno):
  if numero_uno>0:
    return math.log(numero_uno)
  else:
    print("Solo existe el logaritmo de un úmero mayor cero")

def calcular_seno(angulo_radianes):
  return math.sin(angulo_radianes)

def calcular_coseno(numero_uno):
  return math.cos(numero_uno)

def calcular_tangente(numero_uno):
  return math.tan(numero_uno)

def raiz_cubica(numero_uno):
  return math.cbrt(numero_uno)

def opcion1(numero_uno,numero_dos):
  print("Sumamos los dos valores ingreados:")
  print('La suma es:',calcular_suma(numero_uno,numero_dos))

def opcion2(numero_uno,numero_dos):
  print("Restamos los dos valores ingreados:")
  print(calcular_resta(numero_uno,numero_dos))

def opcion3(numero_uno,numero_dos):
  print("Multiplicamos los dos valores ingreados:")
  print(calcular_multiplicacion(numero_uno,numero_dos))

def opcion4(numero_uno,numero_dos):
  print("Dividimos los dos valores ingreados:")
  if numero_dos!=0:
    print("No se puede dividir por cero")
  else:
    print(calcular_division(numero_uno,numero_dos))

def opcion5(numero_uno,numero_dos):
  print("Elevamos el primer valor al segundo:")
  print(calcular_potencia(numero_uno,numero_dos))

def opcion6(numero_uno):
  print("Calculamos la raíz cuadrada del primer valor ingresado:")
  if numero_uno>0:
    print(calcular_raiz_cuadrada(numero_uno))
  else:
    print("Solo existe la raíz cuadrada de un número mayor cero")

def opcion7(numero_uno):
  print("Calculamos el logaritmo (log10) del primer valor ingresado:")
  if numero_uno>0:
    print(calcular_logaritmo(numero_uno))
  else:
    print("Solo existe el logaritmo de un número mayor cero")

def opcion8(numero_uno):
  print("Calculamos el seno (sin) del primer valor ingresado:")
  print(calcular_seno(numero_uno))

def opcion9(numero_uno):
  print("Calculamos el coseno (cos) del primer valor ingresado:")
  print(calcular_coseno(numero_uno))

def opcion10(numero_uno):
  print("Calculamos la tangente (tan) del primer valor ingresado:")
  print(calcular_tangente(numero_uno))

def opcion11(numero_uno):
  print("Calculamos la raíz cúbica (math.cbrt) del primer valor ingresado:")
  print(raiz_cubica(numero_uno))

def llamar_funciones():
  mostrar_titulo()
  mostrar_menu()
  opciones,numero_uno,numero_dos=ingresar_datos()

  if opciones=="1":
    opcion1(numero_uno,numero_dos)
  if opciones=="2":
    opcion2(numero_uno,numero_dos)
  if opciones=="3":
    opcion3(numero_uno,numero_dos)
  if opciones=="4":
    opcion4(numero_uno,numero_dos)
  if opciones=="5":
    opcion5(numero_uno,numero_dos)
  if opciones=="6":
    opcion6(numero_uno)
  if opciones=="7":
    opcion7(numero_uno)
  if opciones=="8":
    opcion8(numero_uno)
  if opciones=="9":
    opcion9(numero_uno)
  if opciones=="10":
    opcion10(numero_uno)
  if opciones=="11":
    opcion11(numero_uno)

llamar_funciones()

