# -*- coding: utf-8 -*-
"""Estructura de datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4pec-V9Ata9Bb17ILcXjYowfG1SEa-F
"""

#Lista de utiles escolares
utiles_escolares = ["lapiz", "cuaderno", "tijeras", "borrador", "regla", "colores", "marcadores"]
print(utiles_escolares)

#Tupla de herramientas para hacer un dibujo
herramientas_dibujo = ("lapiz HB", "lapiz 2B", "limpiatipos", "sacapuntas", "cartulina opalina", "compaz", "rapidografos")
print(herramientas_dibujo)

#Conjunto de frutos rojos
conjunto_frutosrojos = {"arandano", "fresa", "cereza", "frambuesa", "grosella", "mora"}
print(conjunto_frutosrojos)

#Diccionario de libros

diccionario_libro_CienAñosdeSoledad = {
    "Autor": "Gabriel Garcia Marquez", "Año": "1967", "Genero": "Realismo Magico"
    }
print(diccionario_libro_CienAñosdeSoledad)