# -*- coding: utf-8 -*-
"""Saludos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ev1ejhXYN0qrwGACC5tFIK9V1vDhgps
"""

from datetime import datetime

def saludar_segun_la_hora ():
  hora_actual = datetime.now().hour

  if 6 <= hora_actual <= 12:
    print("¡Buenos días!")
  elif 12 < hora_actual < 19:
    print("¡Buenas tardes!")
  elif 19 <= hora_actual < 24:
    print("¡Buenas noches!")
  else:
        print("Ve a dormir es tarde.")
print (saludar_segun_la_hora())

def saludar():
    hora = int(input("Ingresa la hora (0 a 24): "))

    if 6 <= hora < 12:
        print("¡Buenos días!")

    elif 12 <= hora < 19:
        print("¡Buenas tardes!")

    elif 19 <= hora < 24:
        print("¡Buenas noches!")

    elif 0 <= hora < 6:
        print("¡Hola! Buenos días, aún es de madrugada.")
    else:
        print("Hora no válida")

saludar()