# -*- coding: utf-8 -*-
"""While - Match-calculadora

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrHJi37KQVbEWDeMxsEoLVgi2MYju3wv
"""

def calculadora ():
  while True:
    print("MENÚ")
    print("1. Suma")
    print("2. Resta")
    print("3. Multiplicación")
    print("4. División")
    print("5. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == '5':
      print("¡Gracias por usar la calculadora!, Adios.")
      break

    if opcion in ['1', '2', '3', '4']:
            num_uno = float(input("Ingrese el primer número: "))
            num_dos = float(input("Ingrese el segundo número: "))

            match opcion:
              case '1':
                  print (f"Resultado: {num_uno} + {num_dos} = {num_uno + num_dos}")
              case '2':
                  print (f"Resultado: {num_uno} - {num_dos} = {num_uno - num_dos}")
              case '3':
                  print (f"Resultado: {num_uno} * {num_dos} = {num_uno * num_dos}")
              case '4':
                if num_dos!=0:
                  print (f"Resultado: {num_uno} / {num_dos} = {num_uno / num_dos}")
                else:
                  print("No se puede dividir entre 0")
              case _:
                  print("Opción no válida")
calculadora()